name: neubig_benchmarks
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lmdb=0.9.31
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.3
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==0.32.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==25.3.0
      - bert-score==0.3.13
      - blake3==1.0.6
      - blis==0.7.11
      - cachetools==6.2.0
      - catalogue==2.0.10
      - cbor2==5.7.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - compressed-tensors==0.11.0
      - confection==0.1.5
      - conllu==6.0.0
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - cymem==2.0.13
      - dataclasses-json==0.6.7
      - datasets==4.1.1
      - depyf==0.19.0
      - dill==0.3.7
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - en-ner-bc5cdr-md==0.5.1
      - evaluate==0.4.6
      - faiss-gpu==1.7.2
      - fastapi==0.117.1
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.2.0
      - fastrlock==0.8.3
      - filelock==3.19.1
      - fonttools==4.60.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2023.10.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - handystuff==0.2.2
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.36.0
      - idna==3.10
      - instructor==1.11.3
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.2
      - jsonnet==0.21.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==0.3.27
      - langchain-community==0.3.30
      - langchain-core==0.3.76
      - langchain-openai==0.3.33
      - langchain-text-splitters==0.3.11
      - langcodes==3.5.0
      - langsmith==0.4.31
      - language-data==1.3.0
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - lxml==6.0.2
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.15
      - murmurhash==1.0.15
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.1
      - nmslib-metabrainz==2.1.3
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.109.0
      - openai-harmony==0.0.4
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.3
      - outlines-core==0.2.11
      - pandas==2.3.2
      - partial-json-parser==0.2.1.1.post6
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pillow==11.3.0
      - portalocker==3.2.0
      - preshed==3.0.11
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pybase64==1.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==1.10.24
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydantic-settings==2.11.0
      - pyparsing==3.2.5
      - pysbd==0.3.4
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - ragas==0.3.5
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scikit-network==0.33.3
      - scipy==1.15.3
      - scispacy==0.6.2
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - smart-open==6.4.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.4.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.43
      - srsly==2.5.1
      - starlette==0.48.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.4.0
      - trl==0.23.0
      - typer==0.7.0
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - vllm==0.10.2
      - wasabi==0.10.1
      - watchfiles==1.1.0
      - weasel==0.4.3
      - websockets==15.0.1
      - wrapt==2.0.1
      - xformers==0.0.32.post1
      - xgrammar==0.1.23
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.25.0
prefix: /home/nuri/.conda/envs/neubig_benchmarks
