compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU  # or NO if single GPU only
downcast_bf16: no
fsdp_config: {}
gpu_ids: all   # or a list like [0,1,2,3]
machine_rank: 0
main_training_function: main
mixed_precision: bf16  # can be "no", "fp16", "bf16"
num_machines: 1
num_processes: 1  # if multi-GPU, set = number of GPUs
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false